apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: chatshttp
    role: front
spec:
  selector:
    matchLabels:
      app: flask
      role: front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask
        role: front
    spec:
      containers:
      - name: flask
        image: romain22222/info910_flask
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "0.3"
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: ChatsHTTP
