apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    role: requesthandler
spec:
  selector:
    app: nginx
    role: requesthandler
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
